apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    app: postgres-svc
spec:
  type: NodePort
  ports:
  - name: psgres-port
    port: 5432
    targetPort: 5432
    nodePort: 30032
  selector:
    app: postgres-svc